In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings("ignore")

In [3]:
from sklearn.datasets import load_digits

In [4]:
digits = load_digits()

In [8]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
digits['feature_names']

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [10]:
df = pd.DataFrame(digits['data'], columns=digits['feature_names'])

In [11]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 64 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaled_data = scaler.fit_transform(df)

In [17]:
scaled_data

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [18]:
new_df = pd.DataFrame(scaled_data, columns=digits['feature_names'])

In [19]:
new_df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0  -0.335016  -0.043081   0.274072  -0.664478  -0.844129   
1        0.0  -0.335016  -1.094937   0.038648   0.268751  -0.138020   
2        0.0  -0.335016  -1.094937  -1.844742   0.735366   1.097673   
3        0.0  -0.335016   0.377661   0.744919   0.268751  -0.844129   
4        0.0  -0.335016  -1.094937  -2.551014  -0.197863  -1.020657   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0  -0.409724  -0.125023  -0.059078  -0.624009  ...  -0.757436  -0.209785   
1  -0.409724  -0.125023  -0.059078  -0.624009  ...  -0.757436  -0.209785   
2  -0.409724  -0.125023  -0.059078  -0.624009  ...   0.259230  -0.209785   
3  -0.409724  -0.125023  -0.059078   1.879691  ...   1.072563  -0.209785   
4  -0.409724  -0.125023  -0.059078  -0.624009  ...  -0.757436  -0.209785   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0  -0.023596  -0.299081   0.086719   0.208293  -0.366771  -1.146647   
1  -0.023596  -0.299081  -1.089383  -0.249010   0.849632   0.548561   
2  -0.023596  -0.299081  -1.089383  -2.078218  -0.164037   1.565686   
3  -0.023596  -0.299081   0.282736   0.208293   0.241430   0.379040   
4  -0.023596  -0.299081  -1.089383  -2.306869   0.849632  -0.468564   

   pixel_7_6  pixel_7_7  
0  -0.505670  -0.196008  
1  -0.505670  -0.196008  
2   1.695137  -0.196008  
3  -0.505670  -0.196008  
4  -0.505670  -0.196008  

[5 rows x 64 columns]

In [20]:
from sklearn.decomposition import PCA

In [21]:
pca = PCA(n_components=2)

In [22]:
df_pca = pca.fit_transform(new_df)

In [24]:
df_pca.shape

(1797, 2)

In [25]:
df_pca.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [26]:
component_df = pd.DataFrame(df_pca, columns=['first_component', 'second_component'])

In [27]:
component_df.head()

first_component  second_component
0         1.914226         -0.954496
1         0.588974          0.924648
2         1.302029         -0.317260
3        -3.020775         -0.868791
4         4.528960         -1.093516

In [28]:
pca.explained_variance_

array([7.34477606, 5.83549053])

In [29]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054])

In [30]:
np.cumsum(pca.explained_variance_ratio_)

array([0.12033916, 0.2159497 ])

In [32]:
pca_new = PCA(n_components=4)

In [35]:
df_pca_new = pca_new.fit_transform(new_df)

In [37]:
component_df = pd.DataFrame(df_pca_new, columns=['first_component', 'second_component', 'third_component', 'fourth_component'])

In [38]:
pca_new.explained_variance_

array([7.34477606, 5.83549054, 5.15396113, 3.96623563])

In [39]:
pca_new.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498407])

In [40]:
np.cumsum(pca_new.explained_variance_ratio_)

array([0.12033916, 0.21594971, 0.30039385, 0.36537793])